package edu.rit.croatia.iste422.g6.qf.controller.handler.attribute;

// Package imports
import edu.rit.croatia.iste422.g6.qf.controller.QueryfierManager;
import edu.rit.croatia.iste422.g6.qf.model.QueryfierStorage;
import edu.rit.croatia.iste422.g6.qf.model.db.Attribute;
import edu.rit.croatia.iste422.g6.qf.model.db.AttributeDataType;
import edu.rit.croatia.iste422.g6.qf.view.QueryfierDisplay;

// JavaFX imports
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.control.ChoiceBox;

/**
 * This class is in charge of representing the data types of the selected
 * attribute from the list of attributes belonging to the selected entity in the
 * entity, relationship window.
 * <p>
 * This code handles action events generated by ChoiceBox components. When such
 * an event occurs, it extracts the selected value from the ChoiceBox,
 * identifies the entity and attribute, and sets the attribute's data type
 * accordingly.
 */
public class AttributeDataTypeHandler implements EventHandler<ActionEvent> {

    private final QueryfierDisplay display;
    private final QueryfierStorage storage;
    private final QueryfierManager manager;

    public AttributeDataTypeHandler(QueryfierDisplay display, QueryfierStorage storage, QueryfierManager manager) {
        this.display = display;
        this.storage = storage;
        this.manager = manager;
    }

    @Override
    public void handle(ActionEvent event) {

        if (!(event.getSource() instanceof ChoiceBox)) {
            return;
        }

        ChoiceBox<?> cBox = (ChoiceBox<?>) event.getSource();
        String newAttributeDataType = cBox.getValue().toString();

        final String entityName = this.display.getSelectedEntity();
        final String attributeName = this.display.getSelectedAttribute();

        if (entityName == null || attributeName == null) {
            return;
        }

        final Attribute attribute = this.storage.getAttributeByEntity(entityName, attributeName);
        AttributeDataType dataType = AttributeDataType.valueOf(newAttributeDataType);
        attribute.setDataType(dataType);

        this.manager.setAttributeDataTypeSelection(dataType);
    }

}
